development:
  password: fc2279f0fc15394f15f6fb20644b8020
  theme_id: 163036301
  store: imaginables-2.myshopify.com
  ignores:
  ignore_files:
  - config/settings_data.json
  - "*.png"
  - "*.jpg"
  - "*.mp4"
  refill_rate: 2
  bucket_size: 40
  concurrency: 4
