development:
  password: fc2279f0fc15394f15f6fb20644b8020
  theme_id: 163958477
<<<<<<< HEAD
=======
  store: imaginables-2.myshopify.com
  ignores:
  ignore_files:
  - config/settings_data.json
  - "*.mp4"
  refill_rate: 2
  bucket_size: 40
  concurrency: 4
oscar:
  password: fc2279f0fc15394f15f6fb20644b8020
  theme_id: 126896641
  store: imaginables-2.myshopify.com
  ignores:
  ignore_files:
  - config/settings_data.json
  - "*.mp4"
  refill_rate: 2
  bucket_size: 40
  concurrency: 4
george:
  password: fc2279f0fc15394f15f6fb20644b8020
  theme_id: 163036301
>>>>>>> oscar@elkfox.com
  store: imaginables-2.myshopify.com
  ignores:
  ignore_files:
  - config/settings_data.json
  - "*.mp4"
  refill_rate: 2
  bucket_size: 40
  concurrency: 4
